services:
  nifi:                                                         #Nifi Application
    build: .
    container_name: nifi                                        #container Name
    restart: always                                             #Restart policy
    ports:
      - 8081:8080                                               #Host_Port:Container_path ,nifi will be access over the port number 8081
    environment:
      SINGLE_USER_CREDENTIALS_USERNAME: admin                   #NIFI_username
      SINGLE_USER_CREDENTIALS_PASSWORD: Polarisnifi@47          #NIFI_Password
      NIFI_WEB_HTTP_PORT: 8080                                  #NIFI_HTTP_PORT
      NIFI_WEB_PROXY_HOST: <server_ip>:8081

    volumes:
      - nifi-data:/opt/nifi/nifi-current/                       #NIFI Application data
      - /mnt/nifi-shares/repos:/scripts                         #Git Repositories for Python Scripts
      - /mnt/nifi-shares/nifi-dumps:/nifi-dumps                 #CSV Files To be Processed
      - /mnt/nifi-shares/venv:/opt/myenv                        #Python Virtual enviorment mounted to nifi to use external python

  nifi-registry:                                                #Nifi Registry
    image: apache/nifi-registry:latest                          #Docker image for Nifi Registry
    container_name: nifi-registry                               #container Name
    restart: always                                             #Restart Policy
    ports:
      - 19090:19090                                             #Host_Port:Container_path , nifi registry will be access over the port number 19090
    environment:
      NIFI_REGISTRY_WEB_HTTP_PORT: 19090                        #Nifi Registry HTTP PORT
      NIFI_REGISTRY_WEB_HTTPS_PORT: 18443                       #Nifi Registry HTTPS PORT
    volumes:
      - nifi-registry-data:/opt/nifi-registry/nifi-registry-current/   # #NIFI Application data

volumes:
  nifi-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/nifi-data
      o: bind
  nifi-registry-data:
    driver: local
    driver_opts:
      type: none
      device: /mnt/nifi-registry-data
      o: bind