services:
  opersyst_be:
    image: github_runner:latest
    container_name: github_runner
    restart: always
    environment:
      - REPO=<USERNAME>/<REPO>
      - TOKEN=<Github Personal Access TOKEN>
    volumes:
    -  data:/home/docker/

volumes:
  data: